[package]
name = "gtk4-rs_boilerplate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { package="gtk4", version="0.4.6"}
adw = { package="libadwaita", version="0.1.0"}